{% set name = "redbiom" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biocore/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c1386cb3e6aa406f829b5003e6b784576421cc266ca98e424d1908b8510e820f

build:
  noarch: python
  number: 0
  entry_points:
    - redbiom=redbiom.commands:cli

requirements:
  host:
    - python >=3.5
    - pip
    - numpy

  run:
    - python >=3.5
    - click
    - h5py
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - biom-format >=2.1.5
    - nltk
    - joblib
    - requests
    - scikit-bio >=0.4.2

test:
  imports:
    - redbiom
    - redbiom.admin

  commands:
    - redbiom --help

about:
  home: https://github.com/biocore/redbiom
  license: BSD-3
  license_family: BSD
  license_file: COPYING.txt
  summary: 'redbiom: a sample and feature discovery system'
  doc_url: https://github.com/biocore/redbiom
  dev_url: https://github.com/biocore/redbiom
  description: |
    redbiom is a cache service for sample metadata and sample data.

    If used, please cite "redbiom: a Rapid Sample Discovery and Feature 
    Characterization System. Daniel McDonald, Benjamin Kaehler, Antonio 
    Gonzalez, Jeff DeReus, Gail Ackermann, Clarisse Marotz, 
    Gavin Huttley, Rob Knight mSystems 2019, 4:4."
extra:
  recipe-maintainers:
    - wasade
